name: Deploy-Pre

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch for preview'
        required: true
        type: string

concurrency:
  group: deploy-pre

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Build with VitePress
        run: pnpm docs:build

      - name: Push gh-pages-pre
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .vitepress/dist
          publish_branch: gh-pages-pre

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy-Pre
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        allenvs: true
        script: |
          cd /data/wwwroot/pre.goravel.dev/ && git pull origin gh-pages-pre
<<<<<<< HEAD
=======
          
>>>>>>> 81a4c40 (add action)
