name: Deploy

on:
  push:
    branches: [ master ]   # 推送到master自动触发
  workflow_dispatch:       # 支持网页手动触发

concurrency:
  group: deploy
  cancel-in-progress: true  # 新构建到来取消旧构建

permissions:
  contents: write  # 必须：允许action写git分支(gh‑pages)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Build with VitePress
        run: pnpm docs:build

      - name: Push gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .vitepress/dist
          publish_branch: gh-pages